services:
  - type: web
    name: yt-downloader-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: BOT_TOKEN
        sync: false
